<a href="https://colab.research.google.com/github/ikros98/Minecraft-settlement-GAN/blob/main/minecraft_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# code for GDrive
from google.colab import drive
drive.mount('/content/gdrive/')
import sys
sys.path.append('/content/gdrive/MyDrive/FProject')
folder = '/content/gdrive/MyDrive/FProject/'

In [1]:
# auto reload
%load_ext autoreload
%autoreload 2

In [4]:
!pip install nbtlib
!git clone https://ikros98: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@github.com/ikros98/Minecraft-settlement-GAN.git
%cd Minecraft-settlement-GAN/

Cloning into 'Minecraft-settlement-GAN'...
remote: Enumerating objects: 3795, done.
remote: Counting objects: 100% (3795/3795), done.
remote: Compressing objects: 100% (3696/3696), done.
remote: Total 3795 (delta 240), reused 3648 (delta 97), pack-reused 0
Receiving objects: 100% (3795/3795), 14.33 MiB | 23.55 MiB/s, done.
Resolving deltas: 100% (240/240), done.
/content/Minecraft-settlement-GAN


In [2]:
%cd Minecraft-settlement-GAN/

/content/Minecraft-settlement-GAN


In [ ]:
!git pull

Everything up-to-date


In [3]:
# colab
folder = '/content/Minecraft-settlement-GAN/'
# local
#folder = '/Users/ikros/Documents/GitHub/Minecraft-settlement-GAN/'

In [4]:
import SchematicTools
from schematic import SchematicFile
import numpy as np
import SchematicTools
from PIL import Image
import os
import pandas as pd
import plotly.express as px
import tensorflow as tf

My prova

In [ ]:
# this cleans transforms all the cubes in concrete
simpleWorlds = SchematicTools.simplify(SchematicTools.loadArea(folder + 'mcedit settlement generator/0.schematic'))
#exporting after simpleWorlds became
exportSchematic = SchematicFile(shape=simpleWorlds.shape)
exportSchematic.blocks = simpleWorlds
exportSchematic.save(folder + "mcedit settlement generator/sampledExample.schematic")

My prova 2

In [ ]:
# it cleans the file from unnecessary blocks
simpleWorlds = SchematicTools.simplify2(SchematicTools.loadArea(folder + 'mcedit settlement generator/0.schematic'))
#exporting after simpleWorlds became
exportSchematic = SchematicFile(shape=simpleWorlds.shape)
exportSchematic.blocks = simpleWorlds
exportSchematic.save(folder + "mcedit settlement generator/sampledExample.schematic")

In [ ]:
# cleaning all the schematics file from not useful 
for file in os.listdir(folder + "dataset808020/"):
    settlement = SchematicTools.simplify2(SchematicTools.loadArea(folder + "dataset808020/" + file))
    exportSchematic = SchematicFile(shape=settlement.shape)
    exportSchematic.blocks = settlement
    exportSchematic.save(folder + "clean dataset/" + file)

In [ ]:
# creating a csv file with the cleaned settlements
l = []
for file in os.listdir(folder + "clean dataset/"):
    settlement = SchematicTools.loadArea(folder + "clean dataset/" + file)
    l.append(settlement.ravel())
dataset = pd.DataFrame(l)
dataset.to_csv('out.csv')

In [5]:
# function to load the entire dataset
def load_dataset():
    l = []
    for file in os.listdir(folder + "dataset808016/"):
        settlement = SchematicTools.simplify(SchematicTools.loadArea(folder + "dataset808016/" + file))
        l.append(settlement)
    x = np.array(l)
    return (x)

X = load_dataset()
X = X.reshape(X.shape[0], X.shape[1], X.shape[2], X.shape[3], 1) #?? to fix float 32, maybe int

In [6]:
print(np.unique(X[0].flatten()))
print(X.shape)

[False  True]
(500, 16, 80, 80, 1)


In [ ]:
# normalizing the images to [-1, 1]
def normalise(settlement):
  settlement = tf.cast(settlement, tf.float32)
  settlement = (settlement / 69.5) - 1
  return settlement

prova = normalise(X[0])

In [ ]:
np.unique(prova.numpy().flatten())

array([ True])

In [9]:
from tensorflow.keras import layers
# have to understand how to manage the 30 that becomes 28

def make_generator_model():
    model = tf.keras.Sequential()
    model.add(layers.Dense(5*20*20*256, use_bias=False, input_shape=(100,)))
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    model.add(layers.Reshape((5, 20, 20, 256)))
    assert model.output_shape == (None, 5, 20, 20, 256) # Note: None is the batch size

    model.add(layers.Conv3DTranspose(128, (5, 5, 5), strides=(1, 1, 1), padding='same', use_bias=False))
    assert model.output_shape == (None, 5, 20, 20, 128)
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    model.add(layers.Conv3DTranspose(64, (5, 5, 5), strides=(2, 2, 2), padding='same', use_bias=False))
    assert model.output_shape == (None, 10, 40, 40, 64)
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    model.add(layers.Conv3DTranspose(1, (5, 5, 5), strides=(2, 2, 2), padding='same', use_bias=False, activation='tanh'))
    assert model.output_shape == (None, 20, 80, 80, 1)

    return model

def make_discriminator_model():
    model = tf.keras.Sequential()
    model.add(layers.Conv3D(64, (5, 5, 5), strides=(2, 2, 2), padding='same',
                                     input_shape=[20, 80, 80, 1]))
    model.add(layers.LeakyReLU())
    model.add(layers.Dropout(0.3))

    model.add(layers.Conv3D(128, (5, 5, 5), strides=(2, 2, 2), padding='same'))
    model.add(layers.LeakyReLU())
    model.add(layers.Dropout(0.3))

    model.add(layers.Flatten())
    model.add(layers.Dense(1))

    return model

In [ ]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import os
import PIL
import time
from IPython.display import clear_output

BUFFER_SIZE = 1000
BATCH_SIZE = 64

noise_dim = 100
num_examples_to_generate = 16

train_dataset = tf.data.Dataset.from_tensor_slices(X).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)

generator = make_generator_model()

noise = tf.random.normal([num_examples_to_generate, noise_dim])
generated_image = generator(noise, training=False)
"""
#plt.imshow(generated_image[0, :, :, :, 0], cmap='gray')
from mpl_toolkits.mplot3d import Axes3D
def make_ax(grid=False):
    fig = plt.figure()
    ax = fig.gca(projection='3d')
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    ax.set_zlabel("z")#
    ax.grid(grid)
    return ax

ax = make_ax(True)
ax.voxels(generated_image[0, :, :, :, 0], edgecolors='gray', shade=False)
plt.show()"""

discriminator = make_discriminator_model()
decision = discriminator(generated_image)
print (decision)

# This method returns a helper function to compute cross entropy loss
cross_entropy = tf.keras.losses.BinaryCrossentropy(from_logits=True)

def discriminator_loss(real_output, fake_output):
    real_loss = cross_entropy(tf.ones_like(real_output), real_output)
    fake_loss = cross_entropy(tf.zeros_like(fake_output), fake_output)
    total_loss = real_loss + fake_loss
    return total_loss

def generator_loss(fake_output):
    return cross_entropy(tf.ones_like(fake_output), fake_output)

generator_optimizer = tf.keras.optimizers.Adam(1e-3)
discriminator_optimizer = tf.keras.optimizers.Adam(1e-3)

checkpoint_dir = './training_checkpoints'
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt")
checkpoint = tf.train.Checkpoint(generator_optimizer=generator_optimizer,
                                 discriminator_optimizer=discriminator_optimizer,
                                 generator=generator,
                                 discriminator=discriminator)

EPOCHS = 400
noise_dim = 100
num_examples_to_generate = 16

# You will reuse this seed overtime (so it's easier)
# to visualize progress in the animated GIF)
seed = tf.random.normal([num_examples_to_generate, noise_dim])

# Notice the use of `tf.function`
# This annotation causes the function to be "compiled".
@tf.function
def train_step(images):
    noise = tf.random.normal([BATCH_SIZE, noise_dim])

    with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:
      generated_images = generator(noise, training=True)

      real_output = discriminator(images, training=True)
      fake_output = discriminator(generated_images, training=True)

      gen_loss = generator_loss(fake_output)
      disc_loss = discriminator_loss(real_output, fake_output)

    gradients_of_generator = gen_tape.gradient(gen_loss, generator.trainable_variables)
    gradients_of_discriminator = disc_tape.gradient(disc_loss, discriminator.trainable_variables)

    generator_optimizer.apply_gradients(zip(gradients_of_generator, generator.trainable_variables))
    discriminator_optimizer.apply_gradients(zip(gradients_of_discriminator, discriminator.trainable_variables))

def train(dataset, epochs):
  for epoch in range(epochs):
    start = time.time()

    for image_batch in dataset:
      train_step(image_batch)

    # Produce images for the GIF as you go
    #clear_output(wait=True)
    #generate_and_save_images(generator, epoch + 1, seed)

    # Save the model every 5 epochs
    if (epoch + 1) % 20 == 0:
      checkpoint.save(file_prefix = checkpoint_prefix)

    print ('Time for epoch {} is {} sec'.format(epoch + 1, time.time()-start))

def generate_and_save_images(model, epoch, test_input):
  # Notice `training` is set to False.
  # This is so all layers run in inference mode (batchnorm).
  predictions = model(test_input, training=False)


  preview = np.empty((0, 80 * example_grid,3), np.uint8)
  for i in range(example_grid):
      row = np.empty((80, 0, 3), np.uint8)
      for j in range(example_grid):
          imageR = predictions[i*example_grid + j, :, :, :, 0] * 127.5 + 127.5
          imageG = np.average(imageR, axis=0)
          image = np.stack((imageR[0], imageG, imageG), axis=2)
          row = np.hstack((row, image))
      preview = np.vstack((preview, row))

  outputimage = PIL.Image.fromarray(preview.astype(np.uint8))
  outputimage.save('image_at_epoch_{:04d}.png'.format(epoch))
  return outputimage

train(train_dataset, EPOCHS)

In [13]:
from tensorflow.keras import layers
import random 

def make_generator_model(sig = False, batch_size=64):
  output_size, half, forth, eighth, sixteenth = 80, 40, 20, 10, 5
  output_size_h, half_h, forth_h, eighth_h, sixteenth_h = 16, 8, 4, 2, 1
  gf_dim = 256 # Dimension of gen filters in first conv layer

  model = tf.keras.Sequential()
  
  model.add(layers.Dense(gf_dim*sixteenth_h*sixteenth*sixteenth, kernel_initializer=tf.random_normal_initializer(stddev=0.02)))
  model.add(layers.Reshape((sixteenth_h, sixteenth, sixteenth, gf_dim)))
  model.add(layers.BatchNormalization(gamma_initializer=tf.random_normal_initializer(1., 0.02)))
  model.add(layers.ReLU())

  model.add(layers.Conv3DTranspose(gf_dim, [eighth_h, eighth, eighth], strides=(2, 2, 2), padding='same', use_bias=False))
  model.add(layers.BatchNormalization(gamma_initializer=tf.random_normal_initializer(1., 0.02)))
  model.add(layers.ReLU())

  model.add(layers.Conv3DTranspose(gf_dim/2, [forth_h, forth, forth], strides=(2, 2, 2), padding='same', use_bias=False))
  model.add(layers.BatchNormalization(gamma_initializer=tf.random_normal_initializer(1., 0.02)))
  model.add(layers.ReLU())

  model.add(layers.Conv3DTranspose(gf_dim/4, [forth_h, forth, forth], strides=(2, 2, 2), padding='same', use_bias=False))
  model.add(layers.BatchNormalization(gamma_initializer=tf.random_normal_initializer(1., 0.02)))
  model.add(layers.ReLU())

  model.add(layers.Conv3DTranspose(gf_dim/8, [output_size_h, output_size, output_size], strides=(2, 2, 2), padding='same', use_bias=False))
  model.add(layers.Reshape([batch_size, output_size_h, output_size, output_size]))

  if sig: 
    model.add(layers.Activation('sigmoid'))
  else:
    model.add(layers.Activation('tanh'))
  
  return model

def make_discriminator_model(sig = False, output_units = 1):
  #inputs = tf.reshape(inputs,[batch_size,output_size[0],output_size[1],output_size[2],1])
  df_dim = 32 # Dimension of discrim filters in first conv layer

  model = tf.keras.Sequential()

  model.add(layers.Conv3D(df_dim, (4, 4, 4), strides=(2, 2, 2), input_shape=[16, 80, 80, 1],  activation=tf.keras.layers.LeakyReLU(), padding='same'))
  
  model.add(layers.Conv3D(df_dim*2, (4, 4, 4), strides=(2, 2, 2), activation=tf.keras.layers.LeakyReLU(), padding='same'))
  
  model.add(layers.Conv3D(df_dim*4, (4, 4, 4), strides=(2, 2, 2), activation=tf.keras.layers.LeakyReLU(), padding='same'))
  
  model.add(layers.Conv3D(df_dim*8, (4, 4, 4), strides=(2, 2, 2), activation=tf.keras.layers.LeakyReLU(), padding='same'))
  
  model.add(layers.Flatten())

  model.add(layers.Dense(output_units, kernel_initializer=tf.random_normal_initializer(stddev=0.02)))

  if sig: 
    model.add(layers.Activation('sigmoid'))

  return model

In [14]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import os
import PIL
import time
from IPython.display import clear_output

BUFFER_SIZE = 1000
BATCH_SIZE = 256
EPOCHS = 400

noise_dim = 100
num_examples_to_generate = 16

train_dataset = tf.data.Dataset.from_tensor_slices(X).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)

generator = make_generator_model()

noise = tf.random.normal([BATCH_SIZE, 200], 0, 1)
#noise           = tf.random_normal((BATCHSIZE, 200), 0, 1)
#noise = tf.random.normal([num_examples_to_generate, noise_dim])
#generated_image = generator(noise, training=False)
"""
#plt.imshow(generated_image[0, :, :, :, 0], cmap='gray')
from mpl_toolkits.mplot3d import Axes3D
def make_ax(grid=False):
    fig = plt.figure()
    ax = fig.gca(projection='3d')
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    ax.set_zlabel("z")#
    ax.grid(grid)
    return ax

ax = make_ax(True)
ax.voxels(generated_image[0, :, :, :, 0], edgecolors='gray', shade=False)
plt.show()"""

discriminator = make_discriminator_model()
#decision = discriminator(generated_image)
#print (decision)

# This method returns a helper function to compute cross entropy loss
cross_entropy = tf.keras.losses.BinaryCrossentropy(from_logits=True)

def discriminator_loss(real_output, fake_output):
    real_loss = cross_entropy(tf.ones_like(real_output), real_output)
    fake_loss = cross_entropy(tf.zeros_like(fake_output), fake_output)
    total_loss = real_loss + fake_loss
    return total_loss

def generator_loss(fake_output):
    return cross_entropy(tf.ones_like(fake_output), fake_output)

generator_optimizer = tf.keras.optimizers.Adam(0.0025, beta_1=0.5)
discriminator_optimizer = tf.keras.optimizers.Adam(0.00005, beta_1=0.5)

checkpoint_dir = './training_checkpoints'
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt")
checkpoint = tf.train.Checkpoint(generator_optimizer=generator_optimizer,
                                 discriminator_optimizer=discriminator_optimizer,
                                 generator=generator,
                                 discriminator=discriminator)

# You will reuse this seed overtime (so it's easier)
# to visualize progress in the animated GIF)
seed = tf.random.normal([num_examples_to_generate, noise_dim])

# Notice the use of `tf.function`
# This annotation causes the function to be "compiled".
@tf.function
def train_step(images):
    noise = tf.random.normal([BATCH_SIZE, 200], 0, 1)
    #noise = tf.random.normal([BATCH_SIZE, noise_dim])

    with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:
      generated_3d = generator(noise, training=True)

      real_output = discriminator(images, training=True)
      fake_output = discriminator(generated_3d, training=True)

      gen_loss = generator_loss(fake_output)
      disc_loss = discriminator_loss(real_output, fake_output)

    gradients_of_generator = gen_tape.gradient(gen_loss, generator.trainable_variables)
    gradients_of_discriminator = disc_tape.gradient(disc_loss, discriminator.trainable_variables)

    generator_optimizer.apply_gradients(zip(gradients_of_generator, generator.trainable_variables))
    discriminator_optimizer.apply_gradients(zip(gradients_of_discriminator, discriminator.trainable_variables))

def train(dataset, epochs):
  for epoch in range(epochs):
    start = time.time()

    for image_batch in dataset:
      train_step(image_batch)

    # Produce images for the GIF as you go
    #clear_output(wait=True)
    #generate_and_save_images(generator, epoch + 1, seed)

    # Save the model every 5 epochs
    if (epoch + 1) % 20 == 0:
      checkpoint.save(file_prefix = checkpoint_prefix)

    print ('Time for epoch {} is {} sec'.format(epoch + 1, time.time()-start))

def generate_and_save_images(model, epoch, test_input):
  # Notice `training` is set to False.
  # This is so all layers run in inference mode (batchnorm).
  predictions = model(test_input, training=False)


  preview = np.empty((0, 80 * example_grid,3), np.uint8)
  for i in range(example_grid):
      row = np.empty((80, 0, 3), np.uint8)
      for j in range(example_grid):
          imageR = predictions[i*example_grid + j, :, :, :, 0] * 127.5 + 127.5
          imageG = np.average(imageR, axis=0)
          image = np.stack((imageR[0], imageG, imageG), axis=2)
          row = np.hstack((row, image))
      preview = np.vstack((preview, row))

  outputimage = PIL.Image.fromarray(preview.astype(np.uint8))
  outputimage.save('image_at_epoch_{:04d}.png'.format(epoch))
  return outputimage

train(train_dataset, EPOCHS)

NameError: ignored

In [ ]:
def jpp(vec, vals):
    ss = np.searchsorted(vals, vec)
    a = vals[ss - 1]
    b = vals[np.minimum(len(vals) - 1, ss)]
    return np.where(np.fabs(vec - a) < np.fabs(vec - b), a, b)

world = SchematicTools.simplify2(SchematicTools.loadArea(folder + 'mcedit settlement generator/0.schematic'))
blocks_type = np.unique(world.flatten())

prova = generator(seed, training=False)
prova = prova[0, :, :, :, 0].numpy().astype(int)
prova = jpp(prova.flatten(), blocks_type)
prova.reshape(20, 80, 80)
#exportSchematic = SchematicFile(shape=prova.shape)
#exportSchematic.blocks = prova
#exportSchematic.save(folder + "mcedit settlement generator/first trial clean.schematic")

In [ ]:
np.unique(prova.flatten())

array([0, 1])

In [ ]:
#completely differente file that manages the generation of structures
def generateSettlements(num_examples_to_generate, noise_dim):
  #'training' is set to False.
  # this is so all layers run in inference mode (batchnorm).
  settlements = generator(tf.random.normal([num_examples_to_generate, noise_dim]), training=False)
  
  for i in range(num_examples_to_generate):
    settlement = settlements[i, :, :, :, 0] * 0.5 + 0.5
    exportArea = settlement.numpy()#dtype=np.uint8) #uint8??
    exportSchematic = SchematicFile(shape=exportArea.shape)
    exportSchematic.blocks = exportArea
    exportSchematic.save("mcedit settlement generator/" + str(i) + ".schematic")

"""
generator = make_generator_model()
discriminator = make_discriminator_model()
generator_optimizer = tf.keras.optimizers.Adam(1e-3)
discriminator_optimizer = tf.keras.optimizers.Adam(1e-3)

cross_entropy = tf.keras.losses.BinaryCrossentropy(from_logits=True)

checkpoint_dir = './training_checkpoints'
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt")
checkpoint = tf.train.Checkpoint(generator_optimizer=generator_optimizer,
                                 discriminator_optimizer=discriminator_optimizer,
                                 generator=generator,
                                 discriminator=discriminator)
checkpoint.restore(tf.train.latest_checkpoint(checkpoint_dir)).expect_partial()"""

generateSettlements(5, 100)

In [ ]:
prova = SchematicTools.loadArea("mcedit settlement generator/4.schematic")
print(prova)
print(np.unique(prova.flatten()))

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
[0 1]
