<a href="https://colab.research.google.com/github/ikros98/Minecraft-settlement-GAN/blob/main/minecraft_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# code for GDrive
from google.colab import drive
drive.mount('/content/gdrive/')
import sys
sys.path.append('/content/gdrive/MyDrive/FProject')
folder = '/content/gdrive/MyDrive/FProject/'

In [ ]:
# auto reload
%load_ext autoreload
%autoreload 2

In [ ]:
!pip install nbtlib
!git clone https://ikros98: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@github.com/ikros98/Minecraft-settlement-GAN.git
%cd Minecraft-settlement-GAN/
#import sys
#sys.path.append('/content/Minecraft-settlement-GAN')

Cloning into 'Minecraft-settlement-GAN'...
remote: Enumerating objects: 3280, done.
remote: Counting objects: 100% (3280/3280), done.
remote: Compressing objects: 100% (3185/3185), done.
remote: Total 3280 (delta 232), reused 3141 (delta 94), pack-reused 0
Receiving objects: 100% (3280/3280), 12.61 MiB | 34.53 MiB/s, done.
Resolving deltas: 100% (232/232), done.
/content/Minecraft-settlement-GAN


In [ ]:
%cd Minecraft-settlement-GAN/

[Errno 2] No such file or directory: 'Minecraft-settlement-GAN/'
/content/Minecraft-settlement-GAN


In [ ]:
!git pull

remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 6 (delta 3), reused 6 (delta 3), pack-reused 0
Unpacking objects: 100% (6/6), done.
From https://github.com/ikros98/Minecraft-settlement-GAN
   759601f..84024ba  main       -> origin/main
Updating 759601f..84024ba
Fast-forward
 .DS_Store                                           | Bin 10244 -> 10244 bytes
 mcedit settlement generator/.DS_Store               | Bin 6148 -> 6148 bytes
 mcedit settlement generator/0.schematic             | Bin 394019 -> 6568 bytes
 .../sampledExample.schematic                        | Bin 384124 -> 0 bytes
 4 files changed, 0 insertions(+), 0 deletions(-)
 mode change 100644 => 100755 mcedit settlement generator/0.schematic
 delete mode 100644 mcedit settlement generator/sampledExample.schematic


In [ ]:
# colab
folder = '/content/Minecraft-settlement-GAN/'
# local
#folder = '/Users/ikros/Documents/GitHub/Minecraft-settlement-GAN/'

In [ ]:
import SchematicTools
from schematic import SchematicFile
import numpy as np
import SchematicTools
from PIL import Image
import os
import pandas as pd
import plotly.express as px

My prova

In [ ]:
# this cleans transforms all the cubes in concrete
simpleWorlds = SchematicTools.simplify(SchematicTools.loadArea(folder + 'mcedit settlement generator/0.schematic'))
#exporting after simpleWorlds became
exportSchematic = SchematicFile(shape=simpleWorlds.shape)
exportSchematic.blocks = simpleWorlds
exportSchematic.save(folder + "mcedit settlement generator/sampledExample.schematic")

My prova 2

In [ ]:
# it cleans the file from unnecessary blocks
simpleWorlds = SchematicTools.simplify2(SchematicTools.loadArea(folder + 'mcedit settlement generator/0.schematic'))
#exporting after simpleWorlds became
exportSchematic = SchematicFile(shape=simpleWorlds.shape)
exportSchematic.blocks = simpleWorlds
exportSchematic.save(folder + "mcedit settlement generator/sampledExample.schematic")

In [ ]:
# cleaning all the schematics file from not useful 
for file in os.listdir(folder + "dataset808020/"):
    settlement = SchematicTools.simplify2(SchematicTools.loadArea(folder + "dataset808020/" + file))
    exportSchematic = SchematicFile(shape=settlement.shape)
    exportSchematic.blocks = settlement
    exportSchematic.save(folder + "clean dataset/" + file)

In [ ]:
# creating a csv file with the cleaned settlements
l = []
for file in os.listdir(folder + "clean dataset/"):
    settlement = SchematicTools.loadArea(folder + "clean dataset/" + file)
    l.append(settlement.ravel())
dataset = pd.DataFrame(l)
dataset.to_csv('out.csv')

In [ ]:
# function to load the entire dataset
def load_dataset():
    l = []
    for file in os.listdir(folder + "clean dataset/"):
        settlement = SchematicTools.loadArea(folder + "clean dataset/" + file)
        l.append(settlement)
    x = np.array(l)
    return (x)
X = load_dataset()
X = X.reshape(X.shape[0], X.shape[1], X.shape[2], X.shape[3], 1) #?? to fix float 32, maybe int

In [ ]:
X.shape

(1000, 30, 80, 80, 1)

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers
# have to understand how to manage the 30 that becomes 28

def make_generator_model():
    model = tf.keras.Sequential()
    model.add(layers.Dense(5*20*20*256, use_bias=False, input_shape=(100,)))
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    model.add(layers.Reshape((5, 20, 20, 256)))
    assert model.output_shape == (None, 5, 20, 20, 256) # Note: None is the batch size

    model.add(layers.Conv3DTranspose(128, (5, 5, 5), strides=(1, 1, 1), padding='same', use_bias=False))
    assert model.output_shape == (None, 5, 20, 20, 128)
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    model.add(layers.Conv3DTranspose(64, (5, 5, 5), strides=(2, 2, 2), padding='same', use_bias=False))
    assert model.output_shape == (None, 10, 40, 40, 64)
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    model.add(layers.Conv3DTranspose(1, (5, 5, 5), strides=(2, 2, 2), padding='same', use_bias=False, activation='tanh'))
    assert model.output_shape == (None, 20, 80, 80, 1)

    return model

def make_discriminator_model():
    model = tf.keras.Sequential()
    model.add(layers.Conv3D(64, (5, 5, 5), strides=(2, 2, 2), padding='same',
                                     input_shape=[20, 80, 80, 1]))
    model.add(layers.LeakyReLU())
    model.add(layers.Dropout(0.3))

    model.add(layers.Conv3D(128, (5, 5, 5), strides=(2, 2, 2), padding='same'))
    model.add(layers.LeakyReLU())
    model.add(layers.Dropout(0.3))

    model.add(layers.Flatten())
    model.add(layers.Dense(1))

    return model

In [ ]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import os
import PIL
import time
from IPython.display import clear_output

BUFFER_SIZE = 1000
BATCH_SIZE = 64

noise_dim = 100
num_examples_to_generate = 16

train_dataset = tf.data.Dataset.from_tensor_slices(X).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)

generator = make_generator_model()

noise = tf.random.normal([num_examples_to_generate, noise_dim])
generated_image = generator(noise, training=False)
"""
#plt.imshow(generated_image[0, :, :, :, 0], cmap='gray')
from mpl_toolkits.mplot3d import Axes3D
def make_ax(grid=False):
    fig = plt.figure()
    ax = fig.gca(projection='3d')
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    ax.set_zlabel("z")#
    ax.grid(grid)
    return ax

ax = make_ax(True)
ax.voxels(generated_image[0, :, :, :, 0], edgecolors='gray', shade=False)
plt.show()"""

discriminator = make_discriminator_model()
decision = discriminator(generated_image)
print (decision)

# This method returns a helper function to compute cross entropy loss
cross_entropy = tf.keras.losses.BinaryCrossentropy(from_logits=True)

def discriminator_loss(real_output, fake_output):
    real_loss = cross_entropy(tf.ones_like(real_output), real_output)
    fake_loss = cross_entropy(tf.zeros_like(fake_output), fake_output)
    total_loss = real_loss + fake_loss
    return total_loss

def generator_loss(fake_output):
    return cross_entropy(tf.ones_like(fake_output), fake_output)

generator_optimizer = tf.keras.optimizers.Adam(1e-3)
discriminator_optimizer = tf.keras.optimizers.Adam(1e-3)

checkpoint_dir = './training_checkpoints'
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt")
checkpoint = tf.train.Checkpoint(generator_optimizer=generator_optimizer,
                                 discriminator_optimizer=discriminator_optimizer,
                                 generator=generator,
                                 discriminator=discriminator)

EPOCHS = 250
noise_dim = 100
num_examples_to_generate = 16

# You will reuse this seed overtime (so it's easier)
# to visualize progress in the animated GIF)
seed = tf.random.normal([num_examples_to_generate, noise_dim])

# Notice the use of `tf.function`
# This annotation causes the function to be "compiled".
@tf.function
def train_step(images):
    noise = tf.random.normal([BATCH_SIZE, noise_dim])

    with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:
      generated_images = generator(noise, training=True)

      real_output = discriminator(images, training=True)
      fake_output = discriminator(generated_images, training=True)

      gen_loss = generator_loss(fake_output)
      disc_loss = discriminator_loss(real_output, fake_output)

    gradients_of_generator = gen_tape.gradient(gen_loss, generator.trainable_variables)
    gradients_of_discriminator = disc_tape.gradient(disc_loss, discriminator.trainable_variables)

    generator_optimizer.apply_gradients(zip(gradients_of_generator, generator.trainable_variables))
    discriminator_optimizer.apply_gradients(zip(gradients_of_discriminator, discriminator.trainable_variables))

def train(dataset, epochs):
  for epoch in range(epochs):
    start = time.time()

    for image_batch in dataset:
      train_step(image_batch)

    # Produce images for the GIF as you go
    #clear_output(wait=True)
    #generate_and_save_images(generator, epoch + 1, seed)

    # Save the model every 5 epochs
    if (epoch + 1) % 5 == 0:
      checkpoint.save(file_prefix = checkpoint_prefix)

    print ('Time for epoch {} is {} sec'.format(epoch + 1, time.time()-start))

def generate_and_save_images(model, epoch, test_input):
  # Notice `training` is set to False.
  # This is so all layers run in inference mode (batchnorm).
  predictions = model(test_input, training=False)


  preview = np.empty((0, 80 * example_grid,3), np.uint8)
  for i in range(example_grid):
      row = np.empty((80, 0, 3), np.uint8)
      for j in range(example_grid):
          imageR = predictions[i*example_grid + j, :, :, :, 0] * 127.5 + 127.5
          imageG = np.average(imageR, axis=0)
          image = np.stack((imageR[0], imageG, imageG), axis=2)
          row = np.hstack((row, image))
      preview = np.vstack((preview, row))

  outputimage = PIL.Image.fromarray(preview.astype(np.uint8))
  outputimage.save('image_at_epoch_{:04d}.png'.format(epoch))
  return outputimage

train(train_dataset, EPOCHS)

tf.Tensor(
[[-3.8721228e-05]
 [-1.1065065e-04]
 [-5.2141208e-05]
 [-1.6891178e-04]
 [-1.1278138e-04]
 [-1.0857244e-04]
 [-1.7839907e-04]
 [ 2.5957732e-05]
 [ 4.5876815e-05]
 [ 6.6600151e-06]
 [-1.6903381e-05]
 [ 7.0180729e-05]
 [ 6.2339959e-06]
 [-1.7459079e-04]
 [-4.1941283e-05]
 [-2.0407180e-05]], shape=(16, 1), dtype=float32)
Time for epoch 1 is 26.094701290130615 sec
Time for epoch 2 is 26.17010998725891 sec
Time for epoch 3 is 25.952904224395752 sec
Time for epoch 4 is 25.27399444580078 sec
Time for epoch 5 is 29.375288009643555 sec
Time for epoch 6 is 24.74080491065979 sec
Time for epoch 7 is 25.708856105804443 sec
Time for epoch 8 is 25.630493640899658 sec
Time for epoch 9 is 25.33682107925415 sec
Time for epoch 10 is 29.319478034973145 sec
Time for epoch 11 is 24.638949632644653 sec
Time for epoch 12 is 25.674129724502563 sec
Time for epoch 13 is 25.617865324020386 sec
Time for epoch 14 is 25.584609270095825 sec
Time for epoch 15 is 29.460440397262573 sec
Time for epoch 16 is 2

In [ ]:
def jpp(vec, vals):
    ss = np.searchsorted(vals, vec)
    a = vals[ss - 1]
    b = vals[np.minimum(len(vals) - 1, ss)]
    return np.where(np.fabs(vec - a) < np.fabs(vec - b), a, b)

world = SchematicTools.simplify2(SchematicTools.loadArea(folder + 'mcedit settlement generator/0.schematic'))
blocks_type = np.unique(world.flatten())

prova = generator(seed, training=False)
prova = prova[0, :, :, :, 0].numpy().astype(int)
prova = jpp(prova.flatten(), blocks_type)
prova.reshape(20, 80, 80)
#exportSchematic = SchematicFile(shape=prova.shape)
#exportSchematic.blocks = prova
#exportSchematic.save(folder + "mcedit settlement generator/first trial clean.schematic")

In [ ]:
np.unique(prova.flatten())

array([0])

In [ ]:
prova = generator(seed, training=False)
prova = prova[0, :, :, :, 0].numpy().astype(int)
np.searchsorted(prova, blocks_type)

ValueError: ignored

In [ ]:
np.unique(prova.flatten())

array([0])

In [ ]:
from SchematicTools import asBoolean
prova = generator(seed, training=False)
prova = prova[0, :, :, :, 0].numpy().astype(np.uint8)#asBoolean??
exportSchematic = SchematicFile(shape=prova.shape)
exportSchematic.blocks = prova
exportSchematic.save(folder + "mcedit settlement generator/first trial.schematic")

In [ ]:
prova = generator(seed, training=False)
prova = prova[0, :, :, :, 0].numpy()
np.unique(prova.flatten())

array([-1.       , -0.9999999, -0.9999998, ...,  0.9999998,  0.9999999,
        1.       ], dtype=float32)

In [ ]:
#??
samples = np.empty((0, SAMPLESIZE, SAMPLESIZE, SAMPLESIZE))
for s in simpleWorlds :
    samples = np.concatenate((samples, sample(s, SAMPLECOUNT, SAMPLESIZE)), axis=0)

sampled (100000, 8, 8, 8)
